📄 ← &i "lib.ua" "Lines"
ExOne ← $ 1abc2
        $ pqr3stu8vwx
        $ a1b2c3d4e5f
        $ treb7uchet
ExTwo ← $ two1nine
        $ eightwothree
        $ abcone2threexyz
        $ xtwone3four
        $ 4nineeightseven2
        $ zoneight234
        $ 7pqrstsixteen

🔢 ← {"zero" "one" "two" "three" "four" "five" "six" "seven" "eight" "nine"}
⓵ ← /+ ∵(parse ⊂⊃⊢(⊢⇌) ▽≠10 ⊗: +@0 ⇡10 .⊔) 📄
⓶ ← /+ ∵(
  ⬚@\s↯¤ ↥5 ⧻. ⊔
  ⊃(▽⊙⍉ ≠10⊡1. ⊟ ⇡⧻. ⊗: +@0 ⇡10)(⊚⍉ ⍜¤ (⊠(⌕⊔) 🔢))
  +×10 ⊃⊢(⊢⇌) ≡⊡1 ⊏⍏.⊂
) 📄
Inp ← &fras "1.txt"

$"1-1P: _" ⓵ ExOne
$"1-1R: _" ⓵ Inp
$"1-2P: _" ⓶ ExTwo
$"1-2R: _" ⓶ Inp
